### ISSUE TITLE
Configurable header name

### ISSUE THREAD

**Issue by asolove** [KineticCafe/marlowe#2]
Hi there!

Thanks for marlowe! I'd love to use this in an app I'm working on, but I would need to make the incoming/outgoing header name configurable to match an existing standard.

Would you be open to reviewing and accepting a PR with that change if I wrote and tested it?

**Comment by thefury** [comment]
Good Morning @asolove.

I think that this would be a good addition to the gem, and I would be happy to add it.

Thanks!
